version: "2"

formatters:
  enable:
    - goimports 
    - golines 

linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader 
    - copyloopvar 
    - cyclop
    - depguard 
    # - dupl 
    - durationcheck 
    - embeddedstructfieldcheck 
    - errcheck 
    - errname 
    - errorlint 
    - exhaustive 
    - exptostd
    - fatcontext
    - forbidigo
    - funcorder
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype 
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - godoclint # disabled - not supported by current golangci-lint version
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - iface
    - ineffassign
    - intrange
    # - iotamixing # disabled - not supported by current golangci-lint version
    - makezero
    - mirror 
    # - mnd # disabled for now, too noisy. Might be useful later
    - musttag
    - nakedret
    - nestif 
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared 
    - promlinter 
    - protogetter 
    - reassign 
    - recvcheck
    # - revive # disabled for now, too noisy. Might be useful later
    - rowserrcheck 
    - sloglint 
    - spancheck 
    - sqlclosecheck 
    - staticcheck
    - testableexamples 
    - testifylint 
    - testpackage
    - tparallel 
    - unconvert 
    - unparam 
    - unused 
    - usestdlibvars 
    - usetesting 
    - wastedassign 
    - whitespace
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0
    depguard:
      rules:
        "deprecated":
          files:
            - "$all"
          deny:
            - pkg: github.com/satori/go.uuid
              desc: Use github.com/google/uuid instead, satori's package is not maintained
            - pkg: github.com/gofrs/uuid$
              desc: Use github.com/gofrs/uuid/v5 or later, it was not a go module before v5
        "non-test files":
          files:
            - "!$test"
          deny:
            - pkg: math/rand$
              desc: Use math/rand/v2 instead, see https://go.dev/blog/randv2
        "non-main files":
          files:
            - "!**/main.go"
          deny:
            - pkg: log$
              desc: Use log/slog instead, see https://go.dev/blog/slog
    errcheck:
      exclude-functions:
      - (io.Closer).Close
        
    mnd:
      ignored-functions:
        - args.Error
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets.*
        - prometheus.LinearBuckets
run:
  timeout: 5m
  tests: false # skip test files