
services:
  auth:
    build:
      context: .
      dockerfile: cmd/auth/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Bootstrap token - set this to secure your bootstrap endpoint
      BOOTSTRAP_TOKEN: your-bootstrap-token-here

      # Database configuration
      AUTH_DATABASE_FILE: /data/auth.db
      AUTH_PEPPER_FILE: /data/pepper

      # JWT configuration
      AUTH_KEY_ID: bartab-auth-key-001
      AUTH_ISSUER: bartab-auth

      # Optional: persist the private key for debugging
      # AUTH_PRIVATE_KEY_PATH: /data/private_key.pem
    volumes:
      # Persist SQLite database
      - auth-data:/data
    restart: unless-stopped

volumes:
  auth-data:
    driver: local
